### ISSUE TITLE
test_cli_error in test_server_q1 is broken?

### ISSUE THREAD

**Issue by OhadRubin** [advanced-system-design/exercise-1#3]
The test test_cli_error is testing for an error when the port is already in use and the option suggested :
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

is causing the tester to hang, to wait for when the port will be free.
After I remove this option from my code I am able to pass the test.

**Comment by dan-gittik** [comment]
There's indeed a problem, which makes it much less deterministic, but a better solution would be to add a .listen() invocation to the tests. See this PR: https://github.com/advanced-system-design/exercise-1/pull/1
